tasks:
  - name: Setup Java 17 and Optimize JVM
    init: |
      echo "Y" | sdk install java 17.0.15-tem
      sdk default java 17.0.15-tem
      java -version
      mvn -version
      mvn clean install
    command: |
      export MAVEN_OPTS="-XX:+UseG1GC -Xms512m -Xmx1024m -Dcom.sun.management.jmxremote=true"
      mvn spring-boot:run -Dspring-boot.run.profiles=dev
ports:
  - port: 8080
    onOpen: open-preview
  - port: 9010
    visibility: public
vscode:
  extensions:
    - vscjava.vscode-spring-boot
    - vscjava.vscode-maven
    - redhat.java
    - Pivotal.vscode-spring-boot
    - eamodio.gitlens
    - humao.rest-client
    - visualvm.visualvm-launcher
